In [4]:
#1.	Convert the Time_spent_Alone column to a NumPy array.
import numpy as np 
import pandas as pd 
df=pd.read_csv('personality_dataset.csv')
convert =np.array(df['Time_spent_Alone'])
print(convert)

[ 4.  9.  9. ...  4. 11.  3.]


In [6]:
#2.	Create an array of the same size as Stage_fear with all values as 0.
import numpy as np
import pandas as pd 
df=pd.read_csv('personality_dataset.csv')
zeroes =np.zeros(len(df['Going_outside']))
print(zeroes)

[0. 0. 0. ... 0. 0. 0.]


In [7]:
#3.	Make an array with the same length as Social_event_attendance, but filled with 1s.
import pandas as pd
import numpy as np 
df=pd.read_csv('personality_dataset.csv')
zeroes =np.ones(len(df['Going_outside']))
print(zeroes)


[1. 1. 1. ... 1. 1. 1.]


In [12]:
#4.	Create an array of shape (3, 3) where every element is 4.
import pandas as pd
import numpy as np
df=pd.read_csv('personality_dataset.csv')
shape =np.full((3,3),4)
shape1 =np.full((3,1),9)
result = np.concatenate((shape,shape1),axis = 1)
print(result)

[[4 4 4 9]
 [4 4 4 9]
 [4 4 4 9]]


In [13]:
#5.	Make a 5x5 matrix where diagonal has 1s and rest are 0s.
import pandas as pd
import numpy as np
df=pd.read_csv('personality_dataset.csv')
matrix =np.eye(5)
print(matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
#6.	Make an uninitialized array with the same shape as Going_outside.
import pandas as pd
import numpy as np
df=pd.read_csv('personality_dataset.csv')
array =np.empty(len(df['Going_outside']))
print(array)

[9.42011424e-312 9.42011323e-312 0.00000000e+000 ... 0.00000000e+000
 0.00000000e+000 0.00000000e+000]


In [17]:
#7.	Create an array with values from 0 to 10, stepping by 2.
import pandas as pd
import numpy as np
df=pd.read_csv('personality_dataset.csv')
array=np.arange(0,11,2)
print(array)

[ 0  2  4  6  8 10]


In [18]:
#8.	Create 5 values evenly spaced between 10 and 20.
df=pd.read_csv('personality_dataset.csv')
array=np.linspace(10,21,5)
print(array)

[10.   12.75 15.5  18.25 21.  ]


In [20]:
#9.	Make a 4x4 identity matrix using another method.
identity =np.identity(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [26]:
#10.	Extract just the diagonal values from a 2D matrix formed by Friends_circle_size.
extract= df['Friends_circle_size'].to_numpy()
matrix =extract[:25].reshape(5,5)
diagonal = np.diag(matrix)
print(diagonal)

[13.  7. 14.  4. 15.]


In [27]:
#11.	What is the shape of the array created from Post_frequency?
shape =np.shape(df['Post_frequency'])
print(shape)

(2900,)


In [28]:
#12.	How many dimensions does the array from Drained_after_socializing have?
dimension =np.ndim(df['Drained_after_socializing'])
print(dimension)

1


In [33]:
#13.	Change the shape of the array made from Personality into shape (len/2, 2) 
import pandas as pd
import numpy as np 
df=pd.read_csv('personality_dataset.csv')
numpy=df['Post_frequency'].to_numpy()
if len(numpy%2)==0:
    reshape = np.reshape(numpy,len(numpy)/2)
    print(reshape)
else:
    print('Cant divide')


Cant divide


In [34]:
#14.	Convert the array from Stage_fear into a 1D copy.
import numpy as numpy
df=df['Friends_circle_size'].to_numpy()
flatten=df.flatten()
print(flatten)

[13.  0.  5. ...  4.  2.  6.]


In [ ]:
#15.	Create a 1D view of Going_outside without copying it.
import pandas as pd
import numpy as np
df=pd.read_csv('personality_dataset.csv')
ravel =np.ravel(df['Going_outside'])
print(ravel)


[ 6.  0.  2. ...  1. nan  6.]


In [38]:
#16.	Flip the rows and columns of a 2D matrix made using Stage_fear and Friends_circle_size.
df=pd.read_csv('personality_dataset.csv')
flip = np.transpose(df[['Stage_fear','Friends_circle_size']])
print(flip)


                     0    1    2     3    4    5    6    7    8     9     ...  \
Stage_fear             No  Yes  Yes    No   No   No   No   No  Yes    No  ...   
Friends_circle_size  13.0  0.0  5.0  14.0  8.0  6.0  7.0  7.0  0.0  13.0  ...   

                    2890 2891 2892 2893  2894 2895  2896 2897 2898 2899  
Stage_fear           Yes  Yes  Yes  NaN    No   No    No  Yes  Yes   No  
Friends_circle_size  1.0  5.0  1.0  4.0  12.0  6.0  14.0  4.0  2.0  6.0  

[2 rows x 2900 columns]


In [41]:
#17.	Remove any dimensions with size 1 from a reshaped version of Post_frequency.
squeeze =np.squeeze(df['Post_frequency'])
print(squeeze)

0       5.0
1       3.0
2       2.0
3       8.0
4       5.0
       ... 
2895    6.0
2896    9.0
2897    0.0
2898    0.0
2899    9.0
Name: Post_frequency, Length: 2900, dtype: float64


In [43]:
#18.	Add an extra dimension to Drained_after_socializing.
expand =np.expand_dims(df['Drained_after_socializing'],axis=1)
print(expand)

[['No']
 ['Yes']
 ['Yes']
 ...
 ['Yes']
 ['Yes']
 ['No']]


In [2]:
#19.	Change the size of the array from Stage_fear to shape (4, 5) directly.
import pandas as pd 
import numpy as np 
df=pd.read_csv('personality_dataset.csv')
size =np.resize(df['Stage_fear'],new_shape=(4,5))
print(size)

[['No' 'Yes' 'Yes' 'No' 'No']
 ['No' 'No' 'No' 'Yes' 'No']
 ['No' 'Yes' 'No' 'No' 'Yes']
 ['No' 'Yes' 'No' 'Yes' 'No']]


In [6]:
#20.	Swap the first and second axes in a 3D array made from stacking columns.
swap =np.swapaxes(df,0,1)
print(swap)

                                0          1          2          3     \
Time_spent_Alone                 4.0        9.0        9.0        0.0   
Stage_fear                        No        Yes        Yes         No   
Social_event_attendance          4.0        0.0        1.0        6.0   
Going_outside                    6.0        0.0        2.0        7.0   
Drained_after_socializing         No        Yes        Yes         No   
Friends_circle_size             13.0        0.0        5.0       14.0   
Post_frequency                   5.0        3.0        2.0        8.0   
Personality                Extrovert  Introvert  Introvert  Extrovert   

                                4          5          6          7     \
Time_spent_Alone                 3.0        1.0        4.0        2.0   
Stage_fear                        No         No         No         No   
Social_event_attendance          9.0        7.0        9.0        8.0   
Going_outside                    4.0        5.0   

c:\Users\rajhe\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\_core\fromnumeric.py:57: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)


In [12]:
#21.	Add a new axis to the Time_spent_Alone array so it becomes 2D.
numpy =df['Time_spent_Alone'].to_numpy()
print(numpy.shape)
twoD =numpy[:,np.newaxis]
print(format(twoD.shape))
twoD1=numpy[np.newaxis,:]
print(format(twoD1.shape))

(2900,)
(2900, 1)
(1, 2900)


In [15]:
#22.	Add Time_spent_Alone and Going_outside
import numpy as np 
add= np.add(df['Time_spent_Alone'],df['Going_outside'])

print(add)

0       10.0
1        9.0
2       11.0
3        7.0
4        7.0
        ... 
2895     9.0
2896     6.0
2897     5.0
2898     NaN
2899     9.0
Length: 2900, dtype: float64


In [ ]:
#23.	Subtract Stage_fear from Drained_after_socializing.
import numpy as np 

df['subtracted_result'] = np.subtract(df['Friends_circle_size'], df['Going_outside'])
print(df[['Friends_circle_size', 'Going_outside', 'subtracted_result']].abs())


In [ ]:
#24.	Multiply Post_frequency and Social_event_attendance.
import numpy as np
df['new_multiple'] =np.multiply(df['Post_frequency'],df['Social_event_attendance'])
print(df[['Post_frequency','Social_event_attendance','new_multiple']])

In [ ]:
#25.	Divide Friends_circle_size by Post_frequency.
import numpy as np
df['Divide']=np.divide(df['Friends_circle_size'],df['Post_frequency'])
print(df[['Divide','Friends_circle_size','Post_frequency']])

In [29]:
#26.	Raise values in Stage_fear to the power of 2.
import numpy as np
df['Power']=np.power(df['Post_frequency'],2)
print(df[['Power','Post_frequency']])

      Power  Post_frequency
0      25.0             5.0
1       9.0             3.0
2       4.0             2.0
3      64.0             8.0
4      25.0             5.0
...     ...             ...
2895   36.0             6.0
2896   81.0             9.0
2897    0.0             0.0
2898    0.0             0.0
2899   81.0             9.0

[2900 rows x 2 columns]


In [33]:
#27.	Find the remainder when Post_frequency is divided by Going_outside.
import numpy as np
df['reminder']=np.mod(df['Post_frequency'],df['Going_outside'])
print(df[['reminder','Post_frequency','Going_outside']])



      reminder  Post_frequency  Going_outside
0          5.0             5.0            6.0
1          NaN             3.0            0.0
2          0.0             2.0            2.0
3          1.0             8.0            7.0
4          1.0             5.0            4.0
...        ...             ...            ...
2895       0.0             6.0            6.0
2896       0.0             9.0            3.0
2897       0.0             0.0            1.0
2898       NaN             0.0            NaN
2899       3.0             9.0            6.0

[2900 rows x 3 columns]


In [35]:
#28.	Do division of Stage_fear by Drained_after_socializing, but keep only the integer part.
import numpy as np
df['floor_division'] =np.floor_divide(df['Post_frequency'],df['Going_outside'])
print(df[['floor_division','Post_frequency','Going_outside']])

      floor_division  Post_frequency  Going_outside
0                0.0             5.0            6.0
1                inf             3.0            0.0
2                1.0             2.0            2.0
3                1.0             8.0            7.0
4                1.0             5.0            4.0
...              ...             ...            ...
2895             1.0             6.0            6.0
2896             3.0             9.0            3.0
2897             0.0             0.0            1.0
2898             NaN             0.0            NaN
2899             1.0             9.0            6.0

[2900 rows x 3 columns]


In [36]:
#29.	Repeat: Find remainder of Friends_circle_size and Time_spent_Alone.
import numpy as np
df['reminder']=np.remainder(df['Friends_circle_size'],df['Time_spent_Alone'])
print(df[['Friends_circle_size','Time_spent_Alone','reminder']])

      Friends_circle_size  Time_spent_Alone  reminder
0                    13.0               4.0       1.0
1                     0.0               9.0       0.0
2                     5.0               9.0       5.0
3                    14.0               0.0       NaN
4                     8.0               3.0       2.0
...                   ...               ...       ...
2895                  6.0               3.0       0.0
2896                 14.0               3.0       2.0
2897                  4.0               4.0       0.0
2898                  2.0              11.0       2.0
2899                  6.0               3.0       0.0

[2900 rows x 3 columns]


In [ ]:
#31.	What is the average of Time_spent_Alone?
average =np.mean(df['Time_spent_Alone'])
print(average)

In [ ]:
#32.	What is the middle value in Stage_fear?
middle =np.median(df['Time_spent_Alone'])
print(middle)

In [ ]:
# 33.	How spread out are the values in Social_event_attendance?
spread=np.std(df['Social_event_attendance'])
print(spread)

In [ ]:
#34.	What is the variation in Going_outside?
variation = np.var(df['Going_outside'])
print(variation)

In [ ]:
#35.	What is the total of Post_frequency?
total =np.sum(df['Post_frequency'])
print(total)

In [ ]:
#36.	What is the smallest value in Friends_circle_size?
total =np.min(df['Friends_circle_size'])
print(total)

In [46]:
#37.	What is the largest value in Drained_after_socializing?
total =np.max(df['Friends_circle_size'])
print(total)

15.0


In [50]:
#38.	What is the value at 75% position in Stage_fear?
total=np.percentile(df['Friends_circle_size'],q=75)
print(total)

nan


In [53]:
#39.	What is the weighted average of Time_spent_Alone if weights are all 1?
weights =np.ones(len(df))
total =np.average(df['Time_spent_Alone'],weights=weights)
print(total)

nan


In [56]:
#40.	What is the range (max-min) of Going_outside?
range =np.ptp(df['Time_spent_Alone'].dropna())
print(range)

11.0


In [57]:
#41.	Calculate the running total of Post_frequency.
range =np.cumsum(df['Post_frequency'])
print(range)

0           5.0
1           8.0
2          10.0
3          18.0
4          23.0
         ...   
2895    10088.0
2896    10097.0
2897    10097.0
2898    10097.0
2899    10106.0
Name: Post_frequency, Length: 2900, dtype: float64


In [58]:
#42.	Find the running product of values in Social_event_attendance.
cumprod =np.cumprod(df['Social_event_attendance'])
print(cumprod)

0       4.0
1       0.0
2       0.0
3       0.0
4       0.0
       ... 
2895    0.0
2896    0.0
2897    0.0
2898    0.0
2899    0.0
Name: Social_event_attendance, Length: 2900, dtype: float64


In [59]:
#43.	Where is Stage_fear equal to Drained_after_socializing?
equal =np.equal(df['Stage_fear'],df['Drained_after_socializing'])
print(equal)

0       True
1       True
2       True
3       True
4       True
        ... 
2895    True
2896    True
2897    True
2898    True
2899    True
Length: 2900, dtype: bool


In [60]:
#44.	In which rows is Time_spent_Alone greater than Friends_circle_size?
equal =np.greater(df['Time_spent_Alone'],df['Friends_circle_size'])
print(equal)

0       False
1        True
2        True
3       False
4       False
        ...  
2895    False
2896    False
2897    False
2898     True
2899    False
Length: 2900, dtype: bool


In [62]:
#45.	In which rows is Going_outside less than Stage_fear?
small = np.less(df['Going_outside'],df['Post_frequency'])
print(small)

0       False
1        True
2       False
3        True
4        True
        ...  
2895    False
2896     True
2897    False
2898    False
2899     True
Length: 2900, dtype: bool


In [65]:
#46.	Replace Post_frequency values below 3 with 0 and leave others as-is.
replace=np.where(df['Post_frequency']<3,0,df['Post_frequency'])
print(replace)

[5. 3. 0. ... 0. 0. 9.]


In [71]:
#47.	Where are both Stage_fear and Drained_after_socializing above 5?
replace =np.logical_and((df['Post_frequency']>5),(df['Friends_circle_size']>5))
print(replace)


0       False
1       False
2       False
3        True
4       False
        ...  
2895     True
2896     True
2897    False
2898    False
2899     True
Length: 2900, dtype: bool


In [73]:
#48.	Where is either Friends_circle_size or Social_event_attendance above 7?
Or =np.logical_or((df['Friends_circle_size']>7),(df['Social_event_attendance']))
print(Or)

0        True
1       False
2        True
3        True
4        True
        ...  
2895     True
2896     True
2897     True
2898     True
2899     True
Length: 2900, dtype: bool


In [74]:
#49.	Are all values in Time_spent_Alone non-zero?
true =np.all(df['Time_spent_Alone'])
print(true)

False


In [75]:
#50.	Is there any value in Drained_after_socializing that is more than 10?
true =np.any(df['Time_spent_Alone']>10)
print(true)


True


In [77]:
#51 51.	Are all values in Stage_fear real numbers (not NaN or infinite)?
Stage_fear =np.isfinite(df['Time_spent_Alone'])
print(Stage_fear)

0       True
1       True
2       True
3       True
4       True
        ... 
2895    True
2896    True
2897    True
2898    True
2899    True
Name: Time_spent_Alone, Length: 2900, dtype: bool


In [78]:
#52.	Are any values in Post_frequency NaN?
NaN = np.isnan(df['Post_frequency'])
print(NaN)

0       False
1       False
2       False
3       False
4       False
        ...  
2895    False
2896    False
2897    False
2898    False
2899    False
Name: Post_frequency, Length: 2900, dtype: bool


In [79]:
#53.	Are any values in Social_event_attendance infinite?
Infinite=np.isinf(df['Social_event_attendance'])
print(Infinite)

0       False
1       False
2       False
3       False
4       False
        ...  
2895    False
2896    False
2897    False
2898    False
2899    False
Name: Social_event_attendance, Length: 2900, dtype: bool


In [80]:
#54.	Do Stage_fear and Friends_circle_size have the exact same values in all rows?
equality =np.array_equal(df['Drained_after_socializing'],df['Friends_circle_size'])
print(equality)

False


In [84]:
#55.	Are Time_spent_Alone and Drained_after_socializing almost equal (small tolerance)?
equality  = np.allclose(df['Time_spent_Alone'],df['Friends_circle_size'])
print(equality)

False


In [85]:
#56.	Are values in Going_outside and Post_frequency nearly the same (row by row)?
values = np.isclose(df['Going_outside'],df['Post_frequency'])
print(values)

[False False  True ... False False False]


In [87]:
#1.	Generate an array of 10 random float values between 0 and 1.
generate  = np.random.rand(10)
print(generate)

[0.3046527  0.67883794 0.30189086 0.9991418  0.53837885 0.68293043
 0.7416431  0.94101844 0.68643064 0.42165477]


In [89]:
#2.	Generate 5 random integers between 10 and 20.
generate1 = np.random.randint(10,20,5)
print(generate1)

[17 19 15 15 17]


In [90]:
#3.	Create an array of 8 values following a normal distribution.
generate2 = np.random.randn(8)
print(generate2)

[ 1.32902414 -0.65594994  1.58018443 -0.31286861 -0.44076383  1.19972413
 -2.29548001  0.02874339]


In [97]:
#4.	Fix the random output so the same values are created every time.
np.random.seed(32)
generate3 =np.random.rand(5)
print(generate3)

[0.85888927 0.37271115 0.55512878 0.95565655 0.7366696 ]


In [98]:
#5.	Randomly select one value from the Personality column.
choice =np.random.choice(df['Personality'])
print(choice)

Extrovert


In [103]:
#6.	Shuffle the array made from Post_frequency in-place.
shuffled_array = df['Post_frequency'].sample(frac=1).reset_index(drop=True).values
np.random.shuffle(shuffled_array)
print(shuffled_array)


[8. 1. 3. ... 4. 7. 1.]


In [104]:
#7.	Create a shuffled copy of the Stage_fear array without changing the original.
shuffled_array =np.random.permutation(df['Post_frequency'])
print(shuffled_array)


[7. 8. 9. ... 1. 2. 0.]


In [105]:
#8.	Generate 10 random float values between 5 and 15 (uniform).
uniform = np.random.uniform(5,15,10)
print(uniform)

[ 6.44940708  7.78865685  8.77026603  7.83276599 11.2173256   5.76219944
 12.90679007 12.04093196 13.40728171  9.03884423]


In [107]:
#9.	Create 6 values with a mean of 0 and standard deviation of 1.
normal =np.random.normal(loc=0,scale=1,size=6)
print(normal)

[ 1.02448537  0.9018583   0.55277812  0.11838766 -0.67745817  0.77347662]


In [109]:
#10.	Generate 5 values from an exponential distribution.
exponential =np.random.exponential(size=5)
print(exponential)

[1.34160952 1.02608731 1.12442081 1.37968794 0.95327654]


In [113]:
#11.	Get the values at index positions 2, 5, and 9 from Going_outside.
values =np.take(df['Post_frequency'].to_numpy(),[2,5,9])
print(values)

[4. 7. 1.]


In [121]:
#12.	Change the value at index 3 in Time_spent_Alone to 99.
Update  = np.put(df['Time_spent_Alone'].to_numpy(),ind=3,v=99)
print(df['Time_spent_Alone'])

0        4.0
1        9.0
2        9.0
3       99.0
4        3.0
        ... 
2895     3.0
2896     3.0
2897     4.0
2898    11.0
2899     3.0
Name: Time_spent_Alone, Length: 2900, dtype: float64


In [ ]:
#13.	Remove the element at index 1 from the Stage_fear array.
Remove = np.delete(df['Post_frequency'].to_numpy(),1)
df=df.drop(index=df.index[1]).reset_index(drop=True)
print(df['Post_frequency'])

0       4.0
1       1.0
2       1.0
3       1.0
4       3.0
       ... 
2889    8.0
2890    1.0
2891    1.0
2892    1.0
2893    9.0
Name: Post_frequency, Length: 2894, dtype: float64


In [ ]:
#14.	Insert the value 50 at index 4 into the Post_frequency array.
insert=np.insert(df['Post_frequency'],obj=3,values=50)
df.loc[len(df)]=[np.nan]*len(df.columns)
df['Post_frequency']=insert
print(df['Post_frequency'])


In [168]:
#15.	What are all the unique values in Friends_circle_size?
unique =np.unique(df['Friends_circle_size'])
print(unique)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. nan]


In [169]:
#16.	At which index does Social_event_attendance have the highest value?
index =np.argmax(df['Social_event_attendance'])
print(index)

24


In [171]:
#17.	At which index is the minimum value in Drained_after_socializing?
indexmin =np.argmin(df['Social_event_attendance'])
print(indexmin)

10


In [174]:
#18.	Sort the indexes of Stage_fear in ascending order.
sort =np.argsort(df['Friends_circle_size'].to_numpy())
print(sort)

[ 453  599  600 ...  569 2016 2897]


In [176]:
#19.	Return a sorted version of Going_outside.
sorted =np.sort(df['Going_outside'].to_numpy())
print(sorted)

[ 0.  0.  0. ... nan nan nan]


In [179]:
#20.	Limit all values in Time_spent_Alone to stay between 2 and 10.
clip =np.clip(df['Time_spent_Alone'],2,10)
print(clip.count())

2831


In [180]:
#21.	What is the shape of the array created from Post_frequency
shape  = np.shape(df['Post_frequency'])
print(shape)

(2898,)


In [181]:
#22.	How many elements are there in the array from Stage_fear?
elements =np.size(df['Stage_fear'])
print(elements)

2898


In [182]:
#23.	How many dimensions does the array from Friends_circle_size have?
dimensions =np.ndim(df['Friends_circle_size'])
print(dimensions)

1


In [183]:
#24.	What is the data type of elements in the Drained_after_socializing array?
data_type = np.dtype(df['Drained_after_socializing'])
print(data_type)

object


In [191]:
#25.	How many bytes does one element in the Social_event_attendance array take?
bytes =np.array(df['Social_event_attendance']).itemsize
print(bytes)

8


In [193]:
#26.	What is the total number of bytes used by the array from Time_spent_Alone?
bytess =np.array(df['Social_event_attendance']).nbytes
print(bytess)


23184


In [196]:
#27.	Make an exact copy of the Going_outside array.
df['copy']=np.copy(df['Going_outside'])
print(df[['Going_outside','copy']])

      Going_outside  copy
0               6.0   6.0
1               4.0   4.0
2               3.0   3.0
3               6.0   6.0
4               6.0   6.0
...             ...   ...
2893            6.0   6.0
2894            NaN   NaN
2895            NaN   NaN
2896            NaN   NaN
2897            NaN   NaN

[2898 rows x 2 columns]


In [ ]:
#28.	Create a view (not a copy) of the Stage_fear array.
view =df['Stage_fear'].to_numpy().view()
print(view)

In [ ]:
#30.	Find the square roots of Stage_fear.
view1=np.sqrt(df['Post_frequency'])
print(view1)

In [5]:
#29.	Multiply a (3x3) matrix A and (3x1) vector B made from your dataset columns.
import numpy as np
A=np.array([[1,2,3],[4,5,6],[2,4,6]])
B=np.array([[2],[4],[6]])
matrix =np.dot(A,B)
print(matrix)

[[28]
 [64]
 [56]]


In [8]:
#30.	Perform matrix multiplication between two 2D arrays made from your data.
import numpy as np
A=np.array([[1,2,3],[2,5,6]])
B=np.array([[2,8,9],[1,8,2]])
C=np.matmul(A,B.T)
print(C)

[[45 23]
 [98 54]]


In [13]:
#31.	Find the inverse of a 2x2 matrix made from some values.
import numpy as np 
A=np.array([[1,2],[4,3]])
B=np.array([[7,9],[8,3]])
C=np.linalg.inv(B)
print(C)

[[-0.05882353  0.17647059]
 [ 0.15686275 -0.1372549 ]]


In [16]:
#32.	What is the determinant of a 3x3 matrix?
import numpy as np
A=np.array([[1,2,3],[2,5,6],[4,8,9]])
C=np.linalg.det(A)
print(C)

-2.9999999999999996


In [25]:
#33.	Find the eigenvalues of a square matrix made from Stage_fear.
import numpy as np 
import pandas as pd
df=pd.read_csv('personality_dataset.csv')
values =df['Post_frequency'].values[:4]
matrix =np.array(values).reshape(2,2)
Eigenvalues =np.linalg.eig(matrix)
print(Eigenvalues)

EigResult(eigenvalues=array([3.62771868, 9.37228132]), eigenvectors=array([[-0.90937671, -0.56576746],
       [ 0.41597356, -0.82456484]]))


In [30]:
#34.	Solve the equation Ax = b, where A and b are arrays from your data.
import numpy as np
import numpy as np 
import pandas as pd
df=pd.read_csv('personality_dataset.csv')
values =df['Post_frequency'].values[:4]
values1=df['Post_frequency'].values[4:8]
A =np.array(values).reshape(2,2)
B=np.array(values1).reshape(2,2)
Solve =np.linalg.solve(A,B)
print(Solve)




[[0.55882353 0.70588235]
 [0.73529412 0.82352941]]


In [ ]:
#35.	What is the sum of the diagonal elements of a 3x3 matrix?
import pandas as pd
import numpy as np
df=pd.read_csv('personality_dataset.csv')
values=df['Post_frequency'].values[:9]
reshape =np.array(values).reshape(3,3)
sum=np.trace(reshape)
print(sum)


In [37]:
#36.	Get only the lower triangle of a 3x3 matrix.
import pandas as pd
import numpy as np
df=pd.read_csv('personality_dataset.csv')
values=df['Post_frequency'].values[:9]
reshape =np.array(values).reshape(3,3)
tril =np.tril(reshape)
print(tril)


[[5. 0. 0.]
 [8. 5. 0.]
 [7. 8. 3.]]


In [39]:
#37.	Get only the upper triangle of a 3x3 matrix.
#36.	Get only the lower triangle of a 3x3 matrix.
import pandas as pd
import numpy as np
df=pd.read_csv('personality_dataset.csv')
values=df['Post_frequency'].values[:9]
reshape =np.array(values).reshape(3,3)
triu=np.triu(reshape)
print(triu)

[[5. 3. 2.]
 [0. 5. 6.]
 [0. 0. 3.]]


In [ ]:
#38.	What is the rank of a matrix created using 3 columns from your data?
import pandas as pd
import numpy as np
df=pd.read_csv('personality_dataset.csv')
values=df['Post_frequency'].values[:9]
reshape =np.array(values).reshape(3,3)
rank=np.linalg.matrix_rank(reshape)
print(rank)

In [41]:
#39.	What is the condition number of a matrix?
import pandas as pd
import numpy as np
df=pd.read_csv('personality_dataset.csv')
values=df['Post_frequency'].values[:9]
reshape =np.array(values).reshape(3,3)
condition =np.linalg.cond(reshape)
print(condition)

16.002743964585505


In [ ]:
#40.	Perform QR decomposition on a 2D matrix made from your data.

import pandas as pd
import numpy as np
df=pd.read_csv('personality_dataset.csv')
values=df['Post_frequency'].values[:4]
reshape =np.array(values).reshape(2,2)
QR=np.linalg.qr(reshape)
print(QR)


QRResult(Q=array([[-0.92847669, -0.37139068],
       [-0.37139068,  0.92847669]]), R=array([[-5.38516481, -5.75655548],
       [ 0.        ,  6.3136415 ]]))


In [43]:
#41.	Perform Singular Value Decomposition on a matrix.
import pandas as pd
import numpy as np
df=pd.read_csv('personality_dataset.csv')
values=df['Post_frequency'].values[:4]
reshape =np.array(values).reshape(2,2)
SVD=np.linalg.svd(reshape)
print(SVD)

SVDResult(U=array([[ 0.52573111,  0.85065081],
       [ 0.85065081, -0.52573111]]), S=array([9.43467835, 3.60372646]), Vh=array([[ 0.45894062,  0.88846694],
       [ 0.88846694, -0.45894062]]))


In [46]:
#	42.	Perform Cholesky decomposition on a symmetric positive-definite matrix.
import pandas as pd
import numpy as np
df=pd.read_csv('personality_dataset.csv')
values=df['Post_frequency'].values[:2]
reshape =np.array([[values[0],values[1]],[values[1],values[0]]])
cholesky =np.linalg.cholesky(reshape)
print(cholesky)


[[2.23606798 0.        ]
 [1.34164079 1.78885438]]


In [ ]:
#43.	Apply Fourier transform to a 1D array made from Post_frequency.
import pandas as pd
import numpy as np
df=pd.read_csv('personality_dataset.csv')
fourier = np.fft.fft(df['Post_frequency'].fillna(df['Post_frequency'].mean()))

print(fourier)

[ 3.56472663e+00+0.j          1.14455088e-01-0.03122616j
  8.66052731e-02+0.02986001j ... -3.31130071e-03+0.02392521j
  8.66052731e-02-0.02986001j  1.14455088e-01+0.03122616j]


In [53]:
#44.	Apply inverse Fourier transform to the result of the above.
import pandas as pd
import numpy as np
df=pd.read_csv('personality_dataset.csv')
fourier = np.fft.ifft(df['Post_frequency'].fillna(df['Post_frequency'].mean()))
print(fourier)

[ 3.56472663e+00+0.j          1.14455088e-01-0.03122616j
  8.66052731e-02+0.02986001j ... -3.31130071e-03+0.02392521j
  8.66052731e-02-0.02986001j  1.14455088e-01+0.03122616j]


In [57]:
#45.	What are the frequencies of the components in the FFT result?
import pandas as pd
import numpy as np
df=pd.read_csv('personality_dataset.csv')
fourier = np.fft.fft(df['Post_frequency'].fillna(df['Post_frequency'].mean()))
length =np.fft.fftfreq(len(fourier))
print(length)


[ 0.          0.00034483  0.00068966 ... -0.00103448 -0.00068966
 -0.00034483]


In [58]:
#46.	Find the phase angle of the FFT result.
import pandas as pd
import numpy as np
df=pd.read_csv('personality_dataset.csv')
fourier = np.fft.fft(df['Post_frequency'].fillna(df['Post_frequency'].mean()))
angle =np.angle(fourier)
print(angle)

[ 0.          0.26634263 -0.33201944 ... -1.70832482  0.33201944
 -0.26634263]


In [59]:
#47.	Extract only the real part from a complex FFT result.
import pandas as pd
import numpy as np
df=pd.read_csv('personality_dataset.csv')
fourier = np.fft.fft(df['Post_frequency'].fillna(df['Post_frequency'].mean()))
real =np.real(fourier)
print(real)


[ 1.03377072e+04  3.31919756e+02  2.51155292e+02 ... -9.60277207e+00
  2.51155292e+02  3.31919756e+02]


In [62]:
#48.	Extract only the imaginary part from a complex FFT result.
import pandas as pd
import numpy as np
df=pd.read_csv('personality_dataset.csv')
fourier =np.fft.fft(df['Post_frequency'].fillna(df['Post_frequency'].mean()))
imaginery = np.imag(fourier)
print(imaginery)


[  0.          90.55587161 -86.59402594 ... -69.38309998  86.59402594
 -90.55587161]


In [72]:
#49.	Get the complex conjugate of a complex number array.
import pandas as pd
import numpy as np

df = pd.read_csv('personality_dataset.csv')

# Step 1: Use fillna on the Pandas Series (before .values)
values = df['Friends_circle_size'].fillna(0).values[:10]

# Step 2: Convert to complex numbers
array = np.array(values, dtype=np.complex128)

# Step 3: Get complex conjugate
conjugate = np.conj(array)

print("Original complex numbers:", array)
print("Complex conjugates:", conjugate)


Original complex numbers: [13.+0.j  0.+0.j  5.+0.j 14.+0.j  8.+0.j  6.+0.j  7.+0.j  7.+0.j  0.+0.j
 13.+0.j]
Complex conjugates: [13.-0.j  0.-0.j  5.-0.j 14.-0.j  8.-0.j  6.-0.j  7.-0.j  7.-0.j  0.-0.j
 13.-0.j]


In [75]:
#50.	Find the difference between each consecutive value in the Stage_fear array.
import pandas as pd
import numpy as np
df =pd.read_csv('personality_dataset.csv')
difference =np.diff(df['Friends_circle_size'])
print(difference)


[-13.   5.   9. ... -10.  -2.   4.]


In [100]:
#1.	Save the Time_spent_Alone array to a binary .npy file.
time  = np.array(df['Time_spent_Alone'])
save = np.save('time_alone.npy',time)
load=np.load('time_alone.npy')
print(load)

[ 4.  9.  9. ...  4. 11.  3.]


In [101]:
#2.	Load the .npy file and display its contents.
time  = np.array(df['Time_spent_Alone'])
save = np.save('time_alone.npy',time)
load=np.load('time_alone.npy')
print(load)


[ 4.  9.  9. ...  4. 11.  3.]


In [102]:
#3.	Save the Stage_fear array as a .txt file with space delimiter.
text =np.array(df['Time_spent_Alone'])
save =np.savetxt('Stage_fear.txt',text,fmt='%s',delimiter=' ')
print(save)

None


In [103]:
#4.	Load the .txt file and check the data.
text =np.array(df['Time_spent_Alone'])
save =np.savetxt('Stage_fear.txt',text,fmt='%s',delimiter=' ')
load=np.loadtxt('Stage_fear.txt')
print(load)


[ 4.  9.  9. ...  4. 11.  3.]


In [104]:
#5.	Load a text file where some values may be missing (simulate or use a real file).
text =np.array(df['Time_spent_Alone'])
save =np.savetxt('Stage_fear.txt',text,fmt='%s',delimiter=' ')
loadmissing=np.genfromtxt('Stage_fear.txt',dtype=str,delimiter='',filling_values='Missing')
print(loadmissing)


['4.0' '9.0' '9.0' ... '4.0' '11.0' '3.0']


In [105]:
#6.	Load binary data directly from a .bin file on disk (assume it was saved already).
load =np.fromfile('time_alone.npy')
print(load)


[1.87585069e-309 1.17119999e+171 5.22741680e-037 ... 4.00000000e+000
 1.10000000e+001 3.00000000e+000]


In [108]:
#7.	Save a NumPy array to disk in binary format for faster access.
array=np.array(df['Time_spent_Alone'],dtype=str)
array.tofile('number.bin')
print('ok')

ok


In [111]:
#8.	Create a NumPy array from a buffer (like a byte string).
array=np.array(df['Time_spent_Alone'],dtype=str)
buffer =np.frombuffer(array)
print(buffer)

[9.76118064e-313 2.37151510e-322 0.00000000e+000 ... 0.00000000e+000
 0.00000000e+000 0.00000000e+000]


In [ ]:
#9.	Generate a NumPy array from a generator that yields values from 0 to 9.
array=np.array(df['Time_spent_Alone'])
gen = (x for x in range(10))
generator =np.fromiter(gen,dtype=float)
print(generator)
    

In [ ]:
#10.	Create a 3x3 array where each value is the sum of its row and column indexes.
array=np.array(df['Time_spent_Alone'].values[:9].reshape(3,3))
sum =np.fromfunction(lambda i,j:i+j,(3,3),dtype=float)
print(sum)

In [ ]:
#11.	Apply a custom function to every value in Post_frequency without a loop.
def square(x):
    return x**2
function =np.vectorize(square)
result =function(df['Post_frequency'])
print(result)

[25.  9.  4. ...  0.  0. 81.]


In [136]:
#12.	View how the values [1, 2, 3] would broadcast against shape (3, 1).
array =np.array([1,2,3]).reshape(3,1)
array2=np.array([4,5,6]).reshape(1,3)
view=np.broadcast(array,array2)
print(view.shape)


(3, 3)


In [139]:
#13.	Force the array [4, 5, 6] to be broadcast to shape (3, 3) and display the result.

array2=np.array([4,5,6])
force= np.broadcast_to(array,(3,3))
print(force.shape)


(3, 3)


In [141]:
#14.	Repeat the full Stage_fear array 3 times.
array=np.array(df['Stage_fear'])
repeat =np.tile(array,3)
print(repeat)

['No' 'Yes' 'Yes' ... 'Yes' 'Yes' 'No']


In [ ]:
#15.	Repeat each value in Friends_circle_size 2 times.
repeat =np.repeat(df['Friends_circle_size'],2)
print(repeat)

In [143]:
#16.	Create a coordinate grid using values from 0 to 4 and 0 to 2.
array =np.array([0,1,2,3,4])
array2 =np.array([0,1,2])
grid=np.meshgrid(array,array2)
print(grid)


(array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]]), array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2]]))


In [145]:
#17.	Create a grid of indices for shape (2, 3).
grid =np.indices((2,3))
print(grid)

[[[0 0 0]
  [1 1 1]]

 [[0 1 2]
  [0 1 2]]]


In [ ]:
#18.	Create a dense multi-dimensional grid from 0 to 3 and 0 to 2.
dense = np.mgrid[0:4,0:3]
print(dense)

In [ ]:
#19.	Create a light open grid from 0 to 3 and 0 to 2.
dense =np.ogrid[0:4,0:3]
print(dense)

In [ ]:
#20.	Open a large .npy file as a memory-mapped array and read it without loading the entire file.
open =np.memmap('time_alone.npy',dtype='float32' ,mode='r',shape=(1000,))
print(open)


In [ ]:
#21.	Change the setting so divide-by-zero does not crash the program — just warn.
crash =np.seterr(divide='warn')
a=np.array([1,2,3])
b=np.array([0,1,0])
print(a/b)

In [ ]:
#22.	Check the current error-handling settings of NumPy.
error =np.geterr()
print(error)

In [ ]:
#23.	Replace all NaN values in Social_event_attendance with 0.
replace =np.nan_to_num(df['Social_event_attendance'])
print(replace)

In [ ]:
#24.	Generate a histogram from the Stage_fear array with 5 bins.
import matplotlib.pyplot as mp
import numpy as np
mp.hist(df['Social_event_attendance'],bins=5,edgecolor='black',linewidth=1.2)
mp.xlabel('Social_event_attendance')
mp.ylabel('frequencies')
mp.title('Social_events')
mp.show()




In [ ]:
#25.	Count how many times each value appears in Post_frequency.
import numpy as np
filter =df['Post_frequency'].dropna().values
integer =filter.astype(int)
count =np.bincount(integer)
for value,total in enumerate(count):
    print(value,total)


In [183]:
#26.	Fit a polynomial of degree 2 to Time_spent_Alone vs Drained_after_socializing.
import pandas as pd
clean =df[['Time_spent_Alone','Friends_circle_size']].dropna()
x=clean['Time_spent_Alone'].values
y=clean['Friends_circle_size'].values
fitpoly =np.polyfit(x,y,2)
print(fitpoly)



[ 0.07512746 -1.66280078 11.32429576]


In [189]:
#27.	Estimate the area under the curve of Stage_fear using basic integration.
estimate =np.trapezoid(df['Friends_circle_size'].dropna())
print(estimate)

17687.5


In [193]:
#28.	Count business days between two sets of dates (e.g., attendance start and end dates).
attendancestart =np.array(['2012-02-01'],dtype='datetime64[D]')
end =np.array(['2012-06-01'],dtype='datetime64[D]')
countb = np.busday_count(attendancestart,end)
print(countb)

[87]


In [199]:
#29.	Create a date array from '2023-01-01' to '2023-01-10' using a NumPy date type.
array =np.arange('2023-01-01','2023-01-10',dtype='datetime64[D]')
print(array)

['2023-01-01' '2023-01-02' '2023-01-03' '2023-01-04' '2023-01-05'
 '2023-01-06' '2023-01-07' '2023-01-08' '2023-01-09']


In [217]:
#30.	Convert the Personality column values to uppercase using NumPy string tools.
import numpy as np

values = df['Personality'].dropna()
safe =np.array(values.astype(str),dtype='U')
uppercase =np.char.upper(safe)
print(uppercase)



['EXTROVERT' 'INTROVERT' 'INTROVERT' ... 'INTROVERT' 'INTROVERT'
 'EXTROVERT']


In [218]:
#31.	How do you convert all values in Stage_fear to uppercase
values =df['Stage_fear'].dropna()
safe=np.array(values.astype(str),dtype='U')
upper =np.char.upper(safe)
print(upper)

['NO' 'YES' 'YES' ... 'YES' 'YES' 'NO']


In [219]:
#32.	How do you convert all values in Personality to lowercase?
values =df['Personality'].dropna()
safe=np.array(values.astype(str),dtype='U')
lower = np.char.lower(safe)
print(lower)


['extrovert' 'introvert' 'introvert' ... 'introvert' 'introvert'
 'extrovert']


In [4]:
#33.	How do you make only the first letter uppercase in each value of Drained_after_socializing?
import numpy as np
import pandas as pd
df=pd.read_csv('personality_dataset.csv')
clean =df['Drained_after_socializing'].dropna()
string = np.array(clean.astype(str),dtype='U')
first_letter =np.char.capitalize(string)
print(first_letter)

['No' 'Yes' 'Yes' ... 'Yes' 'Yes' 'No']


In [5]:
#34.	How do you capitalize the first letter of every word in each value of Stage_fear?
import numpy as np
import pandas as pd
df=pd.read_csv('personality_dataset.csv')
clean =df['Drained_after_socializing'].dropna()
string = np.array(clean.astype(str),dtype='U')
captalize =np.char.title(string)
print(captalize)

['No' 'Yes' 'Yes' ... 'Yes' 'Yes' 'No']


In [7]:
#35.	How do you swap upper-case and lower-case letters in Personality?
df=pd.read_csv('personality_dataset.csv')
filter =df['Personality'].dropna()
convert =np.array(filter.astype(str),dtype='U')
swap =np.char.swapcase(convert)
print(swap)




['eXTROVERT' 'iNTROVERT' 'iNTROVERT' ... 'iNTROVERT' 'iNTROVERT'
 'eXTROVERT']


In [8]:
#36.	How do you remove spaces from both ends of each value in Stage_fear?
df=pd.read_csv('personality_dataset.csv')
filter =df['Stage_fear'].dropna()
convert =np.array(filter.astype(str),dtype='U')
strip =np.char.strip(convert)
print(strip)



['No' 'Yes' 'Yes' ... 'Yes' 'Yes' 'No']


In [ ]:
#37.	How do you remove spaces only from the beginning of each string in Drained_after_socializing?
df=pd.read_csv('personality_dataset.csv')
filter =df['Drained_after_socializing'].dropna()
convert =np.array(filter.astype(str),dtype='U')
space =np.char.lstrip(convert)
print(space)

In [ ]:
#38.	How do you remove spaces only from the end of each string in Personality?
df=pd.read_csv('personality_dataset.csv')
filter =df['Personality'].dropna()
convert =np.array(filter.astype(str),dtype='U')
last =np.char.rstrip(convert)
print(last)



In [11]:
#39.	How do you split each sentence in Stage_fear into separate words?
df=pd.read_csv('personality_dataset.csv')
filter =df['Stage_fear'].dropna()
convert =np.array(filter.astype(str),dtype='U')
split = np.char.split(convert)
print(split)


[list(['No']) list(['Yes']) list(['Yes']) ... list(['Yes']) list(['Yes'])
 list(['No'])]


In [12]:
#40.	How do you split multi-line text in Personality into individual lines?
df=pd.read_csv('personality_dataset.csv')
filter =df['Stage_fear'].dropna()
convert =np.array(filter.astype(str),dtype='U')
lines =np.char.splitlines(convert)
print(lines)


[list(['No']) list(['Yes']) list(['Yes']) ... list(['Yes']) list(['Yes'])
 list(['No'])]


In [16]:
#41.	How do you insert a - between every character in each value of Drained_after_socializing?
df=pd.read_csv('personality_dataset.csv')
filter =df['Stage_fear'].dropna()
convert =np.array(filter.astype(str),dtype='U')
insert =np.char.join('-',convert)
print(insert)

['N-o' 'Y-e-s' 'Y-e-s' ... 'Y-e-s' 'Y-e-s' 'N-o']


In [ ]:
#42.	How do you replace the word "shy" with "confident" in Stage_fear?
df=pd.read_csv('personality_dataset.csv')
filter =df['Stage_fear'].dropna()
convert =np.array(filter.astype(str),dtype='U')
replace=np.char.replace(convert,'Yes','True')
print(replace)

['No' 'Tru' 'Tru' ... 'Tru' 'Tru' 'No']


In [24]:
#43.	How do you center-align each string in Personality using * as padding?
df=pd.read_csv('personality_dataset.csv')
filter =df['Personality'].dropna()
convert =np.array(filter.astype(str),dtype='U')
center =np.char.center(convert,width=20,fillchar='*')
print(center)



['*****Extrovert******' '*****Introvert******' '*****Introvert******' ...
 '*****Introvert******' '*****Introvert******' '*****Extrovert******']


In [25]:
#44.	How do you left-align each value in Stage_fear using - as padding?
df=pd.read_csv('personality_dataset.csv')
filter =df['Personality'].dropna()
convert =np.array(filter.astype(str),dtype='U')
left=np.char.ljust(convert,width=20,fillchar='-')
print(left)


['Extrovert-----------' 'Introvert-----------' 'Introvert-----------' ...
 'Introvert-----------' 'Introvert-----------' 'Extrovert-----------']


In [26]:
#45.How do you right-align each string in Drained_after_socializing using _?
df=pd.read_csv('personality_dataset.csv')
filter =df['Personality'].dropna()
convert =np.array(filter.astype(str),dtype='U')
left=np.char.rjust(convert,width=20,fillchar='_')
print(left)

['___________Extrovert' '___________Introvert' '___________Introvert' ...
 '___________Introvert' '___________Introvert' '___________Extrovert']


In [30]:
#46.	How do you fill each value in Stage_fear with leading zeros until the length becomes 10?
df=pd.read_csv('personality_dataset.csv')
filter =df['Personality'].dropna()
convert =np.array(filter.astype(str),dtype='U')
zero=np.char.zfill(convert,10)
print(zero)

['0Extrovert' '0Introvert' '0Introvert' ... '0Introvert' '0Introvert'
 '0Extrovert']


In [31]:
#47.	How do you find the starting index of the word "fear" in each value of Stage_fear?
df=pd.read_csv('personality_dataset.csv')
filter =df['Personality'].dropna()
convert =np.array(filter.astype(str),dtype='U')
find =np.char.find(convert,'fear')
print(find)


[-1 -1 -1 ... -1 -1 -1]


In [38]:
#48.	How do you raise an error if "calm" is not found in Drained_after_socializing?
df=pd.read_csv('personality_dataset.csv')
filter =df['Personality'].dropna()

convert =np.array(filter.astype(str),dtype='U')
index=np.char.find(convert,'Introvert')
print(index)


[-1  0  0 ...  0  0 -1]


In [45]:
#49.	How many times does the word "social" appear in each Personality value?
df=pd.read_csv('personality_dataset.csv')
filter =df['Personality'].dropna()

convert =np.array(filter.astype(str),dtype='U')
total =np.char.count(convert,'social')
print(total)

[0 0 0 ... 0 0 0]


In [46]:
#50.	Does each string in Stage_fear start with "high"?
df=pd.read_csv('personality_dataset.csv')
filter =df['Personality'].dropna()

convert =np.array(filter.astype(str),dtype='U')
check =np.char.startswith(convert,'high')
print(check)


[False False False ... False False False]


In [47]:
#51.	Does each string in Drained_after_socializing end with "low"?
df=pd.read_csv('personality_dataset.csv')
filter =df['Personality'].dropna()

convert =np.array(filter.astype(str),dtype='U')
check= np.char.endswith(convert,'low')
print(check)


[False False False ... False False False]


In [53]:
#52.	Are all values in Personality made of numeric characters only?
df=pd.read_csv('personality_dataset.csv')
filter =df['Personality'].dropna()

convert =np.array(filter.astype(str),dtype='U')
check=np.char.isnumeric(convert)
print(check)

[False False False ... False False False]


In [54]:
#53.	Do all values in Stage_fear have only alphabetic letters?
df=pd.read_csv('personality_dataset.csv')
filter =df['Stage_fear'].dropna()

convert =np.array(filter.astype(str),dtype='U')
alpha =np.char.isalpha(convert)
print(alpha)


[ True  True  True ...  True  True  True]


In [ ]:
#54.	Are values in Drained_after_socializing entirely digits?
df=pd.read_csv('personality_dataset.csv')
filter =df['Stage_fear'].dropna()

convert =np.array(filter.astype(str),dtype='U')
digit =np.char.isdigit(convert)
print(digit)


In [ ]:
#55.	Are any values in Personality made of only spaces?
df=pd.read_csv('personality_dataset.csv')
filter =df['Stage_fear'].dropna()

convert =np.array(filter.astype(str),dtype='U')
space =np.char.isspace(convert)
print(space)

In [ ]:
#56.	Are all letters in Stage_fear lowercase?
df=pd.read_csv('personality_dataset.csv')
filter =df['Stage_fear'].dropna()

convert =np.array(filter.astype(str),dtype='U')
lower=np.char.islower(convert)
print(lower)


In [58]:
#57.	Are all letters in Drained_after_socializing uppercase?
df=pd.read_csv('personality_dataset.csv')
filter =df['Stage_fear'].dropna()

convert =np.array(filter.astype(str),dtype='U')
upper= np.char.isupper(convert)
print(upper)

[False False False ... False False False]


In [59]:
#58.	Are values in Personality written in title case?
df=pd.read_csv('personality_dataset.csv')
filter =df['Stage_fear'].dropna()

convert =np.array(filter.astype(str),dtype='U')
title =np.char.istitle(convert)
print(title)

[ True  True  True ...  True  True  True]


In [64]:
#59.	Compare values in Stage_fear and Drained_after_socializing element-wise — are they equal?
df=pd.read_csv('personality_dataset.csv')

filter =df[['Stage_fear','Drained_after_socializing']].dropna()

convert =np.array(filter['Stage_fear'].astype(str),dtype='U')
convert2=np.array(filter['Drained_after_socializing'].astype(str),dtype='U')
equality =np.equal(convert,convert2)
print(equality)



[ True  True  True ...  True  True  True]


In [69]:
#60.	How do you join values from Stage_fear and Personality with a space in between?
df=pd.read_csv('personality_dataset.csv')

filter =df[['Stage_fear','Personality']].dropna()

convert =np.array(filter['Stage_fear'].astype(str),dtype='U')
convert2=np.array(filter['Personality'].astype(str),dtype='U')
equality=np.char.add(np.char.add(convert,' '),convert2)
print(equality)

['No Extrovert' 'Yes Introvert' 'Yes Introvert' ... 'Yes Introvert'
 'Yes Introvert' 'No Extrovert']


In [70]:
#1.	What is the mean of Time_spent_Alone?
mean=np.mean(df['Time_spent_Alone'])
print(mean)

4.505816002819881


In [71]:
#2.	What is the median of Going_outside?
median = np.median(df['Going_outside'])
print(median)

nan


In [72]:
#3.	What is the standard deviation of Friends_circle_size?
std=np.std(df['Friends_circle_size'])
print(std)

4.288932987849525


In [73]:
#4.	What is the variance of Post_frequency?
std=np.var(df['Post_frequency'])
print(std)

8.561859845904525


In [74]:
#5.	What is the min value in Social_event_attendance?
min=np.min(df['Social_event_attendance'])
print(min)

0.0


In [75]:
#6.	What is the max value in Time_spent_Alone?
max=np.max(df['Time_spent_Alone'])
print(max)

11.0


In [78]:
#7.	What is the range (ptp) of Post_frequency?
range=np.ptp(df['Post_frequency'].dropna())
print(range)

10.0


In [82]:
#8.	What is the 25th percentile of Going_outside?
percentile =np.percentile(df['Going_outside'].dropna(),25)
print(percentile)

1.0


In [83]:
#9.	What is the 75th percentile of Friends_circle_size?
percentile75=np.percentile(df['Friends_circle_size'].dropna(),75)
print(percentile75)

10.0


In [86]:
#10.	What is the interquartile range of Post_frequency?
quantile =np.quantile(df['Post_frequency'].dropna(),0.25)
print(quantile)

1.0


In [89]:
#11.	What is the skewness of Time_spent_Alone?
from scipy.stats import skew
skew1=skew(df['Time_spent_Alone'].dropna())
print(skew1)

0.38561740281783413


In [90]:
#12.	What is the kurtosis of Going_outside?
from scipy.stats import kurtosis
kurtosis1 =kurtosis(df['Going_outside'].dropna())
print(kurtosis1)

-1.260164632410231


In [96]:
#13.	What is the median absolute deviation of Social_event_attendance?
import numpy as np
clean =df['Social_event_attendance'].dropna()
median=np.median(clean)
mad=np.median(np.abs(clean-median))
print(mad)

2.0


In [ ]:
#14.	What is the mean ignoring NaNs in Time_spent_Alone?
mean=np.mean(df['Time_spent_Alone'].dropna())
print(mean)

In [ ]:
#15.	What is the std ignoring NaNs in Post_frequency?
std=np.std(df['Post_frequency'].dropna())
print(std)

In [ ]:
#16.	What is the variance ignoring NaNs in Friends_circle_size?
variance=np.nanvar(df['Friends_circle_size'].dropna())
print(variance)

In [ ]:
#17.	What is the count of values above the mean in Going_outside?
mean=np.mean(df['Going_outside'].dropna())
count =np.sum(df['Going_outside'].dropna()>mean)
print(count)

In [ ]:
#18.	What is the z-score normalization of Social_event_attendance?
from scipy.stats import zscore
zscore1=zscore(df['Social_event_attendance'],nan_policy='omit')
print(zscore1)

In [ ]:
#19.	What is the cumulative sum of Time_spent_Alone?
cummalative =np.cumsum(df['Time_spent_Alone'].dropna())
print(cummalative)

In [120]:
#20.	What is the mode of Post_frequency?
import numpy as np
value,count =np.unique(df['Post_frequency'].dropna(),return_counts=True)
values =value[np.argmax(count)]
print(values)


2.0


In [122]:
#21.	Create a histogram of Friends_circle_size.
import matplotlib.pyplot as plt
import numpy as np
histogram =np.histogram(df['Friends_circle_size'].dropna())
print(histogram)

(array([387, 274, 537, 301, 270, 165, 281, 134, 271, 203]), array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5, 15. ]))


In [124]:
#22.	Get bin edges for Post_frequency.
import numpy as np
edges =np.histogram_bin_edges(df['Friends_circle_size'].dropna())
print(edges)


[ 0.   1.5  3.   4.5  6.   7.5  9.  10.5 12.  13.5 15. ]


In [128]:
#23.	Count unique values in Going_outside.
import numpy as np
unique=(df['Going_outside'].dropna()).nunique()
print(unique)

8


In [130]:
#24.	Count the number of zeros in Time_spent_Alone.
import numpy as np
zeros =np.sum(df['Time_spent_Alone']==0)
print(zeros)

369


In [135]:
#21.	What is the skewness of Social_event_attendance?
from scipy.stats import skew
skew1 =skew(df['Social_event_attendance'].dropna())
print(skew1)

0.29458578986658907


In [136]:
#22.	What is the kurtosis of Post_frequency?
from scipy.stats import kurtosis
kurtosis1 =kurtosis(df['Post_frequency'].dropna())
print(kurtosis1)

-1.0755257825782525


In [138]:
#23.	What is the 3rd central moment of Friends_circle_size?
from scipy.stats import moment
moment1 =moment(df['Friends_circle_size'].dropna(),3)
print(moment1)


33.51641570202217


In [139]:
#24.	What is the 4th k-statistic of Post_frequency?
from scipy.stats import kstat
kstat1 =kstat(df['Post_frequency'].dropna())
print(kstat1)


8.564880967939072


In [142]:
#25.	What is the variance of the 2nd k-statistic for Social_event_attendance?
from scipy.stats import kstatvar
variance =kstatvar(df['Social_event_attendance'].dropna(),2)
print(variance)


0.02145510109726964


In [ ]:
#26.	What is the normal PDF of Post_frequency values?
from scipy.stats import norm
data =df['Post_frequency'].dropna()
mean=data.mean()
std=data.std()
pdf_value =norm.pdf(data,loc=mean,scale=std)
print(pdf_value)


In [ ]:
#27.	What is the normal CDF of Friends_circle_size values?
from scipy.stats import norm
data=df['Friends_circle_size'].dropna()
mean=data.mean()
std=data.std()
cdf_value =norm.cdf(data,loc=mean,scale=std)
print(cdf_value)


In [148]:
#28.	Generate 10 normal random samples to simulate Time_spent_Alone.
from scipy.stats import norm
data =df['Time_spent_Alone'].dropna()
mean=data.mean()
std=data.std()
random =norm.rvs(loc=mean,scale=std,size=10)
print(random)


[ 7.91616112  2.34753801  3.7805795   5.95808834  5.81662299  5.89433226
  6.57401013 -1.57238982  6.25718761 15.20895513]


In [149]:
#29.	What is the exponential PDF of Social_event_attendance values?
from scipy.stats import expon
clean =df['Social_event_attendance'].dropna()
exponent =expon.pdf(clean)
print(exponent)

[0.01831564 1.         0.36787944 ... 0.36787944 0.36787944 0.00247875]


In [150]:
#30.	Generate exponential random values based on Time_spent_Alone.
from scipy.stats import expon
clean =df['Time_spent_Alone'].dropna()
exponent1=expon.rvs(clean)
print(exponent1)

[ 4.77217     9.22036779  9.85795828 ...  6.51788987 12.0715005
  4.33227161]


In [152]:
#31.	What is the binomial PMF for Post_frequency with n=10, p=0.3?
from scipy.stats import binom
clean =df['Post_frequency'].dropna()
binomial =binom.pmf(clean,n=10,p=0.3)
print(binomial)

[1.02919345e-01 2.66827932e-01 2.33474441e-01 ... 2.82475249e-02
 2.82475249e-02 1.37781000e-04]


In [159]:
#32.	Generate 5 binomial random samples simulating Going_outside.
from scipy.stats import binom
clean =df['Going_outside'].dropna()
binary =np.where(clean>=1,1,0)
p=binary.mean()

rvs =binom.rvs(n=5,p=p,size=5)
print(rvs)

[5 4 4 4 4]


In [161]:
#33.	What is the Poisson PMF of Post_frequency values with λ=2?
from scipy.stats import poisson
clean =df['Post_frequency'].dropna().astype(int)
poisson  = poisson.pmf(clean,mu=2)
print(poisson)


[3.60894089e-02 1.80447044e-01 2.70670566e-01 ... 1.35335283e-01
 1.35335283e-01 1.90949253e-04]


In [ ]:
#34.	Generate Poisson-distributed samples for Post_frequency.
from scipy.stats import poisson
clean =df['Post_frequency'].dropna().astype(int)
poison =poisson.rvs(clean)
print(poison)



In [ ]:
#35.	Compute the uniform PDF for Friends_circle_size.
from scipy.stats import uniform
clean=df['Friends_circle_size'].dropna().astype(int)
min =clean.min()
max=clean.max()
loc=min
scale=max-min

uniform1 =uniform.pdf(clean,loc=loc,scale=scale)
print(uniform1)

In [ ]:
#36.	Generate uniform random samples to simulate Post_frequency.
from scipy.stats import uniform
clean=df['Friends_circle_size'].dropna().astype(int)
min =clean.min()
max=clean.max()
loc=min
scale=max-min
uniform1=uniform.rvs(clean)
print(uniform1)

In [ ]:
#37.Compute the log-normal PDF of Time_spent_Alone.
from scipy.stats import lognorm
clean=df['Time_spent_Alone'].dropna().astype(int)
s=1
loc=0
scale=clean.mean()
norm =lognorm.pdf(clean,s=s,loc=loc,scale=scale)
print(norm)


In [172]:
#38.	Compute the gamma distribution PDF for Friends_circle_size.
from scipy.stats import gamma
clean=df['Friends_circle_size'].dropna().astype(int)
shape=2
loc=0
scale=clean.mean()
gamma1 =gamma.pdf(clean,a=shape,loc=loc,scale=scale)
print(gamma1)


[0.04158641 0.         0.05730629 ... 0.05377375 0.03699103 0.05862806]


In [177]:
#39.	Compute the beta distribution PDF for Social_event_attendance.
from scipy.stats import beta
clean=df['Friends_circle_size'].dropna().astype(int)
x = (clean - clean.min()) / (clean.max() - clean.min())

a=2
b=3
scale=clean.mean()
beta1=beta.pdf(x,a=a,b=b,scale=scale)
print(beta1)

[0.19652552 0.         0.0912481  ... 0.0746475  0.03900039 0.10705183]


In [179]:
#40.	Compute the t-distribution PDF of Time_spent_Alone.
from scipy.stats import t
clean =df['Time_spent_Alone'].dropna()
x=clean
dfree =len(clean)-1
mean=clean.mean()
std=clean.std()
standardise =(x-mean)/std
compute =t.pdf(standardise,df=dfree)
print(compute)



[0.39471215 0.17319084 0.17319084 ... 0.39471215 0.0699043  0.36323066]


In [ ]:
#41.	Generate 5 t-distributed random samples for Post_frequency.
from scipy.stats import t
clean =df['Time_spent_Alone'].dropna()

dfree =len(clean)-1


generate =t.rvs(df=dfree,size=5)
print(generate)



[ 1.01814809  0.99349802  1.20639133 -0.25148442 -0.53736221]


In [ ]:
#42.	Compute the chi-square PDF of Friends_circle_size.
from scipy.stats import chi2
clean =df['Friends_circle_size'].dropna()
dfree=2
compute =chi2.pdf(clean,df=dfree)
print(compute)


In [187]:
#43.	Generate chi-square distributed values for Time_spent_Alone.
from scipy.stats import chi2
clean =df['Time_spent_Alone'].dropna()
dfree=2
generate3 =chi2.rvs(df=dfree,size=8)
print(generate3)

[4.23437021 1.45365899 0.85233573 0.68463731 4.82980792 1.13572447
 1.38612515 1.04171252]


In [192]:
#44.	Compute multivariate normal PDF using Time_spent_Alone and Post_frequency.
from scipy.stats import multivariate_normal
clean = df[['Time_spent_Alone','Post_frequency']].dropna()
data =clean.values
mean=np.mean(data,axis=0)
cov=np.cov(data.T)
compute =multivariate_normal.pdf(clean,mean=mean,cov=cov)
print(compute)


[0.01934809 0.00541907 0.00831809 ... 0.00342468 0.00394179 0.00162568]


In [196]:
#45.	Compute the multinomial PMF for Post_frequency categories.
from scipy.stats import multinomial
clean =df['Post_frequency'].dropna()
low = ((clean >= 0) & (clean <= 2)).sum()
medium = ((clean >= 3) & (clean <= 5)).sum()
high = (clean >= 6).sum()
count =[low,medium,high]
n=sum(count)
p=[0.2,0.3,0.4]
compute1=multinomial.pmf(count,n=n,p=p)
print(compute1)
print(count)


3.7564046940967387e-264
[np.int64(1387), np.int64(615), np.int64(833)]


In [ ]:
#1.	Replace all negative values in Stage_fear with zero using broadcasting.
import pandas as pd
df=pd.read_csv('personality_dataset.csv')
import numpy as np
replace =np.where(df['Post_frequency']<0,0,df['Post_frequency'])
print(replace)

ValueError: either both or neither of x and y should be given

In [ ]:
#2.	Select only those Post_frequency values that are not equal to 0 or 1.
import pandas as pd
import numpy as np
clean=df['Post_frequency'].dropna()
more_clean=clean[((clean)!=0) & ((clean)!=1)]
print(more_clean)

In [ ]:
#3.	Convert Going_outside values to booleans where > 5 is True, others False.
import pandas as pd
import numpy as np
convert =(df['Going_outside']).astype(bool)
print(convert)


In [29]:
#4.	Assign the value 99 to all elements in Drained_after_socializing where values are less than 2.
import pandas as pd
import numpy as np
assign =np.where(df['Post_frequency']<22,99,df['Post_frequency'])
print(assign)


[99. 99. 99. ... 99. 99. 99.]


In [ ]:
#5.	Create a masked array for Friends_circle_size that hides all values above 10.
import pandas as pd
import numpy as np
df = pd.read_csv('personality_dataset.csv')
array=np.array(df['Friends_circle_size'].dropna())
masked = np.ma.masked_greater(array, 10)

print(masked)

In [ ]:
#6.	Calculate how many items are masked in the above array.
import pandas as pd
import numpy as np
df = pd.read_csv('personality_dataset.csv')
array=np.array(df['Friends_circle_size'].dropna())
count =np.ma.count_masked(masked)
print(count)

In [43]:
#7.	Fill all masked values in the masked array with 0.
fill =np.ma.filled(masked,0)
print(fill)

[0. 0. 5. ... 4. 2. 6.]


In [ ]:
#8.	Sort the rows of a 2D array based on the values in the third column.
import pandas as pd
import numpy as np
df=pd.read_csv('personality_dataset.csv')
column=df.columns[2]
argsort=np.argsort(df[column].values,kind='mergesort')
sorted_df =df.iloc[argsort]
print(sorted_df)

In [ ]:
#9.	Find the row in your dataset with the highest value in Time_spent_Alone.
max=np.max(df['Time_spent_Alone'])
print(max)

In [ ]:
#10.	Compare two arrays and return the index where they differ.
column1 =df.columns[0]
column2=df.columns[2]
differ= np.where(df[column1]!=df[column2])
print(differ)


In [ ]:
#11.	Set every second item in Social_event_attendance to 0.
array=np.array(df['Friends_circle_size'])
array[::2]=0
df['Friends_circle_size']=array
print(df['Friends_circle_size'])

In [ ]:
#12.	Reverse each row of a 2D array.
array =np.array(df)
reverse=array[:,::-1]
print(reverse)


In [ ]:
#13.	Combine Stage_fear and Post_frequency into a 2D column stack.
combined =np.column_stack((df['Stage_fear'], df['Post_frequency']))
print(combined)

In [74]:
#14.	Combine Going_outside and Friends_circle_size as a row-wise array.
row=np.vstack((df['Going_outside'],df['Friends_circle_size']))
print(row)

[[ 6.  0.  2. ...  1. nan  6.]
 [ 0.  0.  0. ...  4.  0.  6.]]


In [ ]:
#15.	Convert a flat index (like 17) to its position in a 3x6 shape.
import pandas as pd
import numpy as np
df=pd.read_csv('personality_dataset.csv')
valid =df['Friends_circle_size'].dropna().astype(int)
valid =valid[valid<12]

row=np.unravel_index(valid,shape=(6,2))

print(row)

In [10]:
#16.	Create a view of Stage_fear that updates when the original changes.
import numpy as np
import pandas as pd
df=pd.read_csv('personality_dataset.csv')
array=np.array(df['Going_outside'].dropna())
view=array.view()
print(view)


[6. 0. 2. ... 3. 1. 6.]


In [ ]:
#17.	Find the memory address of Post_frequency in RAM.
df=pd.read_csv('personality_dataset.csv')
array=np.array(df['Post_frequency'])
interface =array.__array_interface__['data'][0]

print(interface) 


In [20]:
#18.	Display the strides of Time_spent_Alone array.
df=pd.read_csv('personality_dataset.csv')
array=np.array(df['Time_spent_Alone'])
strides =array.strides
print(strides)

(8,)


In [ ]:
#19.	Convert a list of strings to a NumPy array of type U (Unicode).
df=pd.read_csv('personality_dataset.csv')
string_fear =np.array(df['Personality'].astype(str),dtype='U')
print(string_fear)

In [ ]:
#20.	Convert a float array into an int array without changing its shape.
df=pd.read_csv('personality_dataset.csv')
int_array=np.array(df['Friends_circle_size'].dropna().astype(int))
print(int_array)

In [27]:
#21.	Cast a structured array from float32 to float64.
int_array=np.array(df['Friends_circle_size'].dropna().astype(np.float64))
print(int_array)

[13.  0.  5. ...  4.  2.  6.]


In [ ]:
#22.	Safely interpret a string of bytes as a NumPy array.
int_array1=np.array(df['Personality'].dropna())
interpret =np.frombuffer(int_array1)
print(interpret)

In [ ]:
#23.	Create a 3D array filled with the object 'Hello'.
array =np.full((2,2,2),'hello')
print(array)

In [ ]:
#24.	Ensure two arrays share the same memory buffer.
a =np.array(df['Friends_circle_size'])
b=np.array(df['Going_outside'])
share=np.shares_memory(a,b)
print(share)


In [ ]:
#25.	Create a structured array with columns: name (str), age (int), score (float).
import pandas as pd
import numpy as np

# Load your dataset
df = pd.read_csv('personality_dataset.csv')

# Confirm column names
print(df.columns.tolist())

# Select required columns and drop missing values
subset = df[['Personality', 'Friends_circle_size', 'Post_frequency']].dropna()

# Define structured array dtype
dtype = [('name', 'U30'), ('age', 'i4'), ('score', 'f4')]

# Build structured array
structured_array = np.array([
    (row['Personality'], int(row['Friends_circle_size']), float(row['Post_frequency']))
    for _, row in subset.iterrows()
])

print(structured_array)






In [ ]:
#37.	Find all contiguous subarrays of length 3 in Stage_fear.
from numpy.lib.stride_tricks import sliding_window_view
array=np.array(df['Stage_fear'].dropna())
window=sliding_window_view(array,window_shape=3)
print(window)




In [ ]:
#38.	Pad a 1D array with values on both sides to make its length 20.
array=np.array(df['Personality'].dropna)
pod =np.pad(array,20)
print(pod)

In [56]:
#39.	Roll Post_frequency values 2 steps forward like circular shift.
array=np.array(df['Post_frequency'].dropna())
roll =np.roll(array,2)
print(roll)

[0. 9. 5. ... 6. 9. 0.]


In [ ]:
#40.	Split Stage_fear into 3 equal parts.
array=np.array(df['Post_frequency'].dropna())
split=np.array_split(array,3)
for i, part in enumerate(split, 1):
    print(f"Part {i}:\n", part, "\n")


In [ ]:
#41.	Replace all diagonal elements of a square array with -1.
import numpy as np
import pandas as pd

# Assuming df is already loaded
data = df['Friends_circle_size'].dropna().to_numpy()

# Make it square — use only the first N values to create an N x N array
n = min(len(data), 5)  # use 5x5 for example; you can use len(data)**0.5 if perfect square

square_array = np.zeros((n, n), dtype=int)

# Fill diagonal with actual values just to demonstrate
np.fill_diagonal(square_array, data[:n])

# Now replace diagonal with -1
np.fill_diagonal(square_array, -1)

print(square_array)


In [ ]:
#42.	Flip a 2D array upside down.
data =df['Friends_circle_size'].dropna()
updown=np.flipud(data)
print(updown)

In [ ]:
#43.	Flip a 2D array left to right.
data =df['Friends_circle_size'].dropna()
array=np.array(data)
dimension =array.reshape(1,-1)
left=np.fliplr(dimension)
print(data)

In [ ]:
#44.	Replace NaNs in Friends_circle_size with average of neighbors.
data = df['Friends_circle_size'].astype(float).to_numpy()

# Find indices where values are NaN
nan_indices = np.where(np.isnan(data))[0]

for idx in nan_indices:
    left = data[idx - 1] if idx - 1 >= 0 else np.nan
    right = data[idx + 1] if idx + 1 < len(data) else np.nan

    neighbors = [v for v in [left, right] if not np.isnan(v)]
    
    if neighbors:
        data[idx] = np.mean(neighbors)

print("Filled array:\n", data)





In [81]:
#45.	Find the longest consecutive sequence of 1s in Social_event_attendance.
data =np.array(df['Social_event_attendance'].dropna().astype(int))
max_count=0
current_count=0
for val in data:
    if val==1:
        current_count+=1
        max_count=max(max_count,current_count)
    else:
        current_count=0
print(max_count)



3


In [ ]:
#46.	Apply a piecewise function to Post_frequencyr: - if value < 3 → 0 - if value between 3–5 → 1 - if value > 5 → 2
import numpy as np
data = df['Post_frequency'].fillna(0).to_numpy()
conditions =[
    data <3,(data >= 3) & (data<=5),data >5
]
values =[0,1,2]
select= np.select(conditions,values)
print(select)

In [ ]:
#47.	Create a lookup table to replace values in Friends_circle_size using a key-value map.
import numpy as np

# Lookup array: index = original value, value = replacement
lookup_array = np.array([0, 10, 20, 30, 40, 50])  # index 1 → 10, index 2 → 20, etc.

# Get values from the column
array = df['Friends_circle_size'].fillna(0).astype(int).to_numpy()

# Make sure all values are valid indices
array[array >= len(lookup_array)] = 0  # Prevent index out of bounds

# Apply lookup
mapped = np.take(lookup_array, array)

print(mapped)


In [91]:
#48.	Compare two arrays and show which values are "almost equal" with a tolerance of 0.001.
a=np.array(df['Friends_circle_size'])
b=np.array(df['Post_frequency'])
isclose =np.isclose(a,b)
print(isclose)

[False False False ... False False False]


In [ ]:
#49.	Identify repeated values in Time_spent_Alone and show the positions.
import numpy as np
import pandas as pd

# Get array from the column
array = np.array(df['Time_spent_Alone'].dropna())

# Find duplicate values and their positions
positions = {}

for idx, val in enumerate(array):
    if val in positions:
        positions[val].append(idx)
    else:
        positions[val] = [idx]

# Keep only values that occur more than once
duplicates = {k: v for k, v in positions.items() if len(v) > 1}

# Display
for val, idxs in duplicates.items():
    print(f"Value {val} is repeated at positions: {idxs}")


In [ ]:
#50.	Convert all integers in Post_frequency to binary strings.
array=np.array(df['Post_frequency'].dropna().astype(int))
binary =np.vectorize(np.binary_repr)(array)
print(binary)

In [103]:
#58.	Count non-zero items in Time_spent_Alone.
array = np.nonzero(df['Time_spent_Alone'].dropna())
sumation =np.count_nonzero(array)
print(sumation)

2467


In [ ]:
#59.	Check which values in Post_frequency are in the list [1, 3, 5].
import numpy as np

# Get the column as array
data = df['Post_frequency'].to_numpy()

# Get all index positions
indices = np.arange(len(data))

# Create a boolean mask for desired positions
mask = np.isin(indices, [1, 3, 5])

# Apply mask to data
selected_values = data[mask]

print(selected_values)



In [108]:
#60.	Get indices of non-zero values in Going_outside.
indices =np.flatnonzero(df['Post_frequency'])
print(indices)

[   0    1    2 ... 2895 2896 2899]


In [ ]:
#61.	What is the Pearson correlation coefficient between Post_frequency and Friends_circle_size?
data = df[['Post_frequency','Friends_circle_size']].dropna()

stds = data.std()
data = data.loc[:, stds != 0]

# Now compute correlation or transformation safely
result = np.corrcoef(data.T)  # or any other function
print(result)


In [114]:
#62.	Compute the covariance matrix of Post_frequency and Time_spent_Alone.
data = df[['Post_frequency','Time_spent_Alone']].dropna()
covariance =np.cov(data)
print(covariance)



[[  0.5  -3.   -3.5 ...  -2.   -5.5   3. ]
 [ -3.   18.   21.  ...  12.   33.  -18. ]
 [ -3.5  21.   24.5 ...  14.   38.5 -21. ]
 ...
 [ -2.   12.   14.  ...   8.   22.  -12. ]
 [ -5.5  33.   38.5 ...  22.   60.5 -33. ]
 [  3.  -18.  -21.  ... -12.  -33.   18. ]]


In [ ]:
#69.	Compute the outer product of Post_frequency and Time_spent_Alone.
subset = df[['Post_frequency', 'Time_spent_Alone']].dropna()
data = subset['Post_frequency'].to_numpy()
b = subset['Time_spent_Alone'].to_numpy()

covariance =np.outer(data,b)
print(covariance)

In [ ]:
#70.	Compute the inner product of Friends_circle_size and Social_event_attendance.
subset = df[['Post_frequency', 'Time_spent_Alone']].dropna()
data = subset['Post_frequency'].to_numpy()
b = subset['Time_spent_Alone'].to_numpy()
inner =np.inner(data,b)
print(inner)

In [123]:
#72.	Generate 10 normally distributed random floats to simulate Post_frequency.
mean = df['Post_frequency'].mean()
std = df['Post_frequency'].std()

random_simulated = np.random.normal(loc=mean, scale=std, size=10)
print(random_simulated)


[ 2.29001293  2.43200575  6.2482785  -2.72816112  1.54449538 -5.48946
  9.63195686  0.46399425  4.40508366  6.63142536]


In [ ]:
#71.	Generate 10 uniform random floats to simulate Going_outside.
import numpy as np
import pandas as pd
df=pd.read_csv('personality_dataset.csv')

df['Post_frequency'] = pd.to_numeric(df['Post_frequency'], errors='coerce')
df['Post_frequency'] = df['Post_frequency'].clip(0, 1).fillna(0.5)  # clip values between 0 and 1, fill NaN with 0.5

distribution = np.random.binomial(n=10, p=df['Post_frequency'])
print(distribution)


[10 10 10 ...  0  0 10]


In [ ]:
#76.	Generate a random permutation of Friends_circle_size.
import numpy as np
import pandas as pd
df=pd.read_csv('personality_dataset.csv')
random =np.random.permutation(df['Friends_circle_size'])
print(random)

In [ ]:
#77.	Set a seed before generating random values for reproducibility.
import numpy as np
import pandas as pd

df = pd.read_csv('personality_dataset.csv')

# Drop NaN values if any
friends = df['Friends_circle_size'].dropna()

# Convert to numeric if needed
friends = pd.to_numeric(friends, errors='coerce').dropna()

# Now generate a random permutation
permuted = np.random.permutation(friends)

print(permuted)


In [ ]:
#75.	Shuffle the Post_frequency values in-place.
import pandas as pd
import numpy as np

df = pd.read_csv('personality_dataset.csv')

# Convert to numeric, drop NaNs
df['Post_frequency'] = pd.to_numeric(df['Post_frequency'], errors='coerce')

# Drop NaNs if you want to shuffle only valid values
valid = df['Post_frequency'].dropna().values.copy()

# Shuffle in-place
np.random.shuffle(valid)

# Assign shuffled values back (only to non-NaN positions)
df.loc[df['Post_frequency'].notna(), 'Post_frequency'] = valid

print(df['Post_frequency'])


In [21]:
#82.	Round the values of Friends_circle_size to the nearest integer.
import pandas as pd
import numpy as np
values =np.round(df['Friends_circle_size'])
print(values)



0       13.0
1        0.0
2        5.0
3       14.0
4        8.0
        ... 
2895     6.0
2896    14.0
2897     4.0
2898     2.0
2899     6.0
Name: Friends_circle_size, Length: 2900, dtype: float64


In [ ]:
#83.	Round down the values of Time_spent_Alone.
values=np.floor(df['Friends_circle_size'])
print(values)

In [ ]:
#84.	Round up the values of Social_event_attendance.
array=np.ceil(df['Social_event_attendance'])
print(array)

In [26]:
#85.	Truncate decimal values in Post_frequency.
array=np.trunc(df['Post_frequency'])
print(array)

0       2.0
1       2.0
2       2.0
3       1.0
4       2.0
       ... 
2895    6.0
2896    3.0
2897    1.0
2898    1.0
2899    2.0
Name: Post_frequency, Length: 2900, dtype: float64


In [ ]:
#86.	Get the sign (+/−) of each value in Friends_circle_size.
array=np.sign(df['Friends_circle_size'])
print(array)

In [ ]:
#88.	Compute the base-10 logarithm of Post_frequency.
log= np.log10(df['Friends_circle_size'])
print(log)

In [ ]:
#87.	Compute the natural log of Post_frequency.
natural= np.log(df['Post_frequency'])
print(natural)

In [ ]:
#89.	Apply the exponential function on Post_frequency.
exponential =np.exp(df['Post_frequency'])
print(exponential)

In [ ]:
#91.	Raise Post_frequency to the power of 3.
power =np.power(df['Friends_circle_size'],3)
print(power)

In [ ]:
#90.	Find the square root of Social_event_attendance.
sqrt =np.sqrt(df['Friends_circle_size'])
print(sqrt)

In [ ]:
#92.	Get the absolute values of Friends_circle_size.
abs=np.abs(df['Friends_circle_size'])
print(abs)

In [34]:
#93.	Compute the total sum of Time_spent_Alone.
sum=np.sum(df['Time_spent_Alone'])
print(sum)

12783.0


In [35]:
#94.	Compute the product of all elements in Post_frequency.
sum=np.prod(df['Post_frequency'])
print(sum)

0.0


In [ ]:
#95.	Compute the column-wise mean of numerical columns.
import pandas as pd
df = pd.read_csv('personality_dataset.csv')

# Compute column-wise mean of numeric columns only
column_means = df.mean(numeric_only=True, axis=0)

print(column_means)


In [38]:
#96.	Compute the row-wise mean (if applicable) of selected columns.
import pandas as pd
df = pd.read_csv('personality_dataset.csv')

# Compute column-wise mean of numeric columns only
column_means = df.mean(numeric_only=True, axis=1)

print(column_means)

0       6.4
1       2.4
2       3.8
3       7.0
4       5.8
       ... 
2895    5.6
2896    7.4
2897    2.0
2898    3.5
2899    6.0
Length: 2900, dtype: float64


In [39]:
#97.	Sort the values in Post_frequency.
import pandas as pd
df=pd.read_csv('personality_dataset.csv')
sort=np.sort(df['Post_frequency'])
print(sort)

[ 0.  0.  0. ... nan nan nan]


In [40]:
#98.	Get the indices that would sort Post_frequency.
import pandas as pd
df=pd.read_csv('personality_dataset.csv')
sort1=np.argsort(df['Post_frequency'])
print(sort1)

0       1902
1        774
2       1848
3        782
4        783
        ... 
2895      41
2896      45
2897      46
2898      51
2899      60
Name: Post_frequency, Length: 2900, dtype: int64


c:\Users\rajhe\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\_core\fromnumeric.py:57: FutureWarning: The behavior of Series.argsort in the presence of NA values is deprecated. In a future version, NA values will be ordered last instead of set to -1.
  return bound(*args, **kwds)


In [ ]:
#99.	Find the index of the minimum value in Time_spent_Alone.
import pandas as pd
df=pd.read_csv('personality_dataset.csv')
sort1=np.argmin(df['Time_spent_Alone'])
print(sort1)


In [42]:
#100.Find the index of the maximum value in Post_frequency.
import pandas as pd
df=pd.read_csv('personality_dataset.csv')
sort2=np.argmax(df['Post_frequency'])
print(sort2)


12
